//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace son_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afisler
    {
        public int Afisid { get; set; }
        public string Baslik { get; set; }
        public int Kategori { get; set; }
        public string Kategoriekle { get; set; }
        public string Aciklama { get; set; }
        public string Fotograf { get; set; }
        public string Wplink { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
