//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace son_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyekayit
    {
        public int uyeid { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
    }
}
